version: '3.6'
services:
  api:
    container_name: recipes-searcher
    image: node:alpine
    command: sh -c './node_modules/.bin/nodemon -r esm app.js'
    working_dir: /usr/app
    volumes:
      - .:/usr/app/
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      PORT: 8080
      HOST: 0.0.0.0